CREATE TABLE `hand_receipts` (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,`filename` text NOT NULL,`receipt_type` text NOT NULL,`uic` text,`unit_name` text,`effective_date` text,`imported_at` text NOT NULL,`imported_by` text NOT NULL,`source_object_key` text,`status` text DEFAULT 'draft' NOT NULL,`total_quantity` integer DEFAULT 0 NOT NULL,`line_group_count` integer DEFAULT 0 NOT NULL,`serialized_count` integer DEFAULT 0 NOT NULL);
CREATE INDEX `idx_receipts_effective_date` ON `hand_receipts` (`effective_date`);
CREATE INDEX `idx_receipts_status` ON `hand_receipts` (`status`);
CREATE TABLE `receipt_lines` (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,`receipt_id` integer NOT NULL,`lin` text,`nsn` text,`nomenclature` text NOT NULL,`quantity` integer DEFAULT 1 NOT NULL,`unit_of_issue` text,`accountability_code` text,FOREIGN KEY (`receipt_id`) REFERENCES `hand_receipts`(`id`));
CREATE INDEX `idx_receipt_lines_receipt` ON `receipt_lines` (`receipt_id`);
CREATE INDEX `idx_receipt_lines_nsn` ON `receipt_lines` (`nsn`);
CREATE TABLE `receipt_serials` (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,`receipt_line_id` integer NOT NULL,`serial_number` text NOT NULL,FOREIGN KEY (`receipt_line_id`) REFERENCES `receipt_lines`(`id`));
CREATE INDEX `idx_receipt_serials_line` ON `receipt_serials` (`receipt_line_id`);
CREATE INDEX `idx_receipt_serials_serial` ON `receipt_serials` (`serial_number`);
CREATE TABLE `property_items` (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,`nsn` text,`nomenclature` text NOT NULL,`serial_number` text,`quantity` integer DEFAULT 1 NOT NULL,`classification` text,`current_custodian` text,`current_location` text,`status` text DEFAULT 'on_hand' NOT NULL,`source_receipt_id` integer,`created_at` text NOT NULL,`retired_at` text,FOREIGN KEY (`source_receipt_id`) REFERENCES `hand_receipts`(`id`));
CREATE UNIQUE INDEX `idx_property_serial` ON `property_items` (`serial_number`);
CREATE INDEX `idx_property_nsn` ON `property_items` (`nsn`);
CREATE INDEX `idx_property_status` ON `property_items` (`status`);
CREATE TABLE `custody_history` (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,`property_item_id` integer NOT NULL,`custodian` text NOT NULL,`location` text,`document_receipt_id` integer,`assigned_at` text NOT NULL,`returned_at` text,`notes` text,FOREIGN KEY (`property_item_id`) REFERENCES `property_items`(`id`),FOREIGN KEY (`document_receipt_id`) REFERENCES `hand_receipts`(`id`));
CREATE INDEX `idx_custody_item_date` ON `custody_history` (`property_item_id`,`assigned_at`);
CREATE TABLE `receipt_reconciliation` (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,`receipt_id` integer NOT NULL,`property_item_id` integer,`serial_number` text,`nsn` text,`discrepancy_type` text NOT NULL,`resolution_status` text DEFAULT 'open' NOT NULL,`resolution_note` text,`resolved_by` text,`resolved_at` text,FOREIGN KEY (`receipt_id`) REFERENCES `hand_receipts`(`id`),FOREIGN KEY (`property_item_id`) REFERENCES `property_items`(`id`));
CREATE INDEX `idx_reconciliation_receipt` ON `receipt_reconciliation` (`receipt_id`);
CREATE INDEX `idx_reconciliation_status` ON `receipt_reconciliation` (`resolution_status`);
CREATE TABLE `property_events` (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,`property_item_id` integer,`receipt_id` integer,`event_type` text NOT NULL,`occurred_at` text NOT NULL,`recorded_by` text NOT NULL,`details` text,FOREIGN KEY (`property_item_id`) REFERENCES `property_items`(`id`),FOREIGN KEY (`receipt_id`) REFERENCES `hand_receipts`(`id`));
CREATE INDEX `idx_property_events_item_date` ON `property_events` (`property_item_id`,`occurred_at`);
CREATE INDEX `idx_property_events_receipt` ON `property_events` (`receipt_id`);
