import { DA_2062_TITLE, UNIT } from "./copy";
import type {
  Actor,
  LedgerDocument,
  LedgerException,
  LoanRecord,
  PropertyItem,
  ReceiptPeriod,
  ReceiptRecord,
} from "./types";

export const DEMO_SOLDIER: Actor = {
  id: "soldier-hale",
  displayName: "J. Hale",
  fullName: "SPC Jordan Hale",
  initials: "JH",
  role: "soldier",
  email: "j.hale@unit.mil",
  grade: "SPC",
};

export const DEMO_PM: Actor = {
  id: "pm-ortiz",
  displayName: "R. Ortiz",
  fullName: "R. Ortiz",
  initials: "RO",
  role: "pm",
  email: "r.ortiz@unit.mil",
  grade: "SFC",
};

export const PHRH = DEMO_PM;

export const people: Actor[] = [DEMO_SOLDIER, DEMO_PM];

export const propertyItems: PropertyItem[] = [
  {
    id: "1",
    nsn: "702501M007142",
    name: "Cisco IRS 1101 Integrated Services Router",
    serial: "FGL2344LR2M",
    quantityRequired: 1,
    quantityOnHand: 1,
    accountabilityClass: "Accountable",
    networkClassification: "Unclassified",
    assignedToId: null,
    assignedToName: null,
    location: "Commo Cage",
    status: "on_hand",
    sourceReceipt: `${UNIT.receiptLabel} · 01 Sep 26`,
    phrhId: PHRH.id,
    phrhName: PHRH.fullName,
    components: [
      {
        id: "1-coei-1",
        kind: "COEI",
        nomenclature: "Power adapter, AC",
        requiredQuantity: 1,
        onHandQuantity: 1,
        serialized: false,
      },
      {
        id: "1-bii-1",
        kind: "BII",
        nomenclature: "Console cable",
        requiredQuantity: 1,
        onHandQuantity: 1,
        serialized: false,
      },
    ],
  },
  {
    id: "2",
    nsn: "580501C949317",
    name: "Telephone, Satellite: 9575A Iridium",
    serial: "300415040404300",
    quantityRequired: 1,
    quantityOnHand: 1,
    accountabilityClass: "Sensitive",
    networkClassification: "Unclassified",
    assignedToId: DEMO_SOLDIER.id,
    assignedToName: DEMO_SOLDIER.fullName,
    location: "Commo Cage",
    status: "signed_for",
    unitTracking: "assigned",
    sourceReceipt: `${UNIT.receiptLabel} · 01 Sep 26`,
    phrhId: PHRH.id,
    phrhName: PHRH.fullName,
    shrHolderId: DEMO_SOLDIER.id,
    shrHolderName: DEMO_SOLDIER.fullName,
    shrDocument: "SHR · Hale · 01 Sep 26",
    components: [
      {
        id: "2-bii-1",
        kind: "BII",
        nomenclature: "Holster / carry case",
        requiredQuantity: 1,
        onHandQuantity: 1,
        serialized: false,
      },
      {
        id: "2-aal-1",
        kind: "AAL",
        nomenclature: "Spare battery",
        requiredQuantity: 2,
        onHandQuantity: 1,
        serialized: false,
      },
    ],
  },
  {
    id: "3",
    nsn: "6130014952839",
    name: "Charger, Battery",
    serial: "013252",
    quantityRequired: 1,
    quantityOnHand: 1,
    accountabilityClass: "Durable",
    networkClassification: "Unclassified",
    assignedToId: DEMO_SOLDIER.id,
    assignedToName: DEMO_SOLDIER.fullName,
    location: "Supply Cage",
    status: "signed_for",
    sourceReceipt: `${UNIT.receiptLabel} · 01 Sep 26`,
    phrhId: PHRH.id,
    phrhName: PHRH.fullName,
    shrHolderId: DEMO_SOLDIER.id,
    shrHolderName: DEMO_SOLDIER.fullName,
    shrDocument: "SHR · Hale · 01 Sep 26",
    components: [],
  },
  {
    id: "4",
    nsn: "589501D050302",
    name: "BHI Mini-SATCOM Antenna Kit",
    serial: null,
    quantityRequired: 1,
    quantityOnHand: 1,
    accountabilityClass: "Accountable",
    networkClassification: "Unclassified",
    assignedToId: DEMO_SOLDIER.id,
    assignedToName: DEMO_SOLDIER.fullName,
    location: "Cage",
    status: "needs_serial_check",
    sourceReceipt: `${UNIT.receiptLabel} · 01 Sep 26`,
    phrhId: PHRH.id,
    phrhName: PHRH.fullName,
    shrHolderId: DEMO_SOLDIER.id,
    shrHolderName: DEMO_SOLDIER.fullName,
    shrDocument: "SHR · Hale · 01 Sep 26",
    components: [
      {
        id: "4-coei-1",
        kind: "COEI",
        nomenclature: "Antenna assembly",
        requiredQuantity: 1,
        onHandQuantity: 1,
        serialized: false,
      },
      {
        id: "4-bii-1",
        kind: "BII",
        nomenclature: "Transit case",
        requiredQuantity: 1,
        onHandQuantity: 1,
        serialized: false,
      },
    ],
  },
  {
    id: "5",
    nsn: "702101C104142",
    name: "Computer, Personal Workstation: E5420",
    serial: "2FSV3K3",
    quantityRequired: 1,
    quantityOnHand: 1,
    accountabilityClass: "Accountable",
    networkClassification: "SIPR",
    assignedToId: null,
    assignedToName: null,
    location: "E2 Desk",
    status: "on_hand",
    sourceReceipt: `${UNIT.receiptLabel} · 01 Sep 26`,
    phrhId: PHRH.id,
    phrhName: PHRH.fullName,
    components: [],
  },
  {
    id: "6",
    nsn: "701001D054717",
    name: "Computer, Laptop: Latitude 7430",
    serial: "J4RC6L3",
    quantityRequired: 1,
    quantityOnHand: 1,
    accountabilityClass: "Accountable",
    networkClassification: "NIPR",
    assignedToId: DEMO_SOLDIER.id,
    assignedToName: DEMO_SOLDIER.fullName,
    location: "Office",
    status: "signed_for",
    unitTracking: "assigned",
    sourceReceipt: `${UNIT.receiptLabel} · 01 Sep 26`,
    phrhId: PHRH.id,
    phrhName: PHRH.fullName,
    shrHolderId: DEMO_SOLDIER.id,
    shrHolderName: DEMO_SOLDIER.fullName,
    shrDocument: "SHR · Hale · 01 Sep 26",
    components: [],
  },
  {
    id: "7",
    nsn: "7021016793258",
    name: "Computer, Digital",
    serial: "GPC1902107",
    quantityRequired: 1,
    quantityOnHand: 1,
    accountabilityClass: "Accountable",
    networkClassification: "SIPR",
    assignedToId: null,
    assignedToName: null,
    location: "Office",
    status: "on_hand",
    sourceReceipt: "Tracker only",
    phrhId: PHRH.id,
    phrhName: PHRH.fullName,
    components: [],
  },
  {
    id: "8",
    nsn: "702101C946392",
    name: "Computer, Personal Workstation: E5420",
    serial: "HDSV3K3",
    quantityRequired: 1,
    quantityOnHand: 0,
    accountabilityClass: "Accountable",
    networkClassification: "SIPR",
    assignedToId: null,
    assignedToName: null,
    location: "Office",
    status: "shortage_recorded",
    sourceReceipt: "Tracker only",
    phrhId: PHRH.id,
    phrhName: PHRH.fullName,
    components: [],
  },
];

export const soldierAssignedSerials = propertyItems
  .filter((item) => item.assignedToId === DEMO_SOLDIER.id)
  .map((item) => item.serial)
  .filter((serial): serial is string => Boolean(serial));

export const exceptions: LedgerException[] = [
  {
    id: "exc-1",
    itemId: "7",
    serial: "GPC1902107",
    item: "Computer, Digital",
    issue: "In computer tracker, absent from 18E hand receipt",
    action: "Verify gaining document or remove from holdings",
    severity: "Review",
    assignedToId: null,
  },
  {
    id: "exc-2",
    itemId: "8",
    serial: "HDSV3K3",
    item: "Dell E5420 Workstation",
    issue: "In computer tracker, absent from 18E hand receipt",
    action: "Locate transfer or Sub-hand receipt (SHR)",
    severity: "Review",
    assignedToId: null,
  },
  {
    id: "exc-3",
    itemId: "4",
    serial: "—",
    item: "BHI Mini-SATCOM Antenna Kit",
    issue: "Receipt quantity 1; serial field is blank",
    action: "Physically verify serial or mark non-serialized",
    severity: "Missing data",
    assignedToId: DEMO_SOLDIER.id,
  },
  {
    id: "exc-4",
    itemId: "2",
    serial: "300415040404300",
    item: "Telephone, Satellite: 9575A Iridium",
    issue: "AAL spare battery on hand 1 of 2 required",
    action: "Record shortage or replenish AAL",
    severity: "Shortage",
    assignedToId: DEMO_SOLDIER.id,
  },
];

export const receipts: ReceiptRecord[] = [
  {
    id: "rcpt-1",
    filename: "18E Hand Receipt.pdf",
    kind: "hand_receipt",
    kindLabel: "Hand receipt",
    uic: UNIT.document,
    effectiveDate: "01 Sep 2026",
    lineGroups: 54,
    totalQuantity: 192,
    status: "Current",
    phrhName: PHRH.fullName,
  },
  {
    id: "rcpt-2",
    filename: "18E Hand Receipt AUG.pdf",
    kind: "hand_receipt",
    kindLabel: "Hand receipt",
    uic: UNIT.document,
    effectiveDate: "01 Aug 2026",
    lineGroups: 53,
    totalQuantity: 190,
    status: "Superseded",
    phrhName: PHRH.fullName,
  },
  {
    id: "rcpt-3",
    filename: "HALE Sub-hand receipt.pdf",
    kind: "sub_hand_receipt",
    kindLabel: "Sub-hand receipt (SHR)",
    uic: UNIT.document,
    effectiveDate: "01 Sep 2026",
    lineGroups: 4,
    totalQuantity: 4,
    status: "Current",
    phrhName: PHRH.fullName,
    shrHolderName: DEMO_SOLDIER.fullName,
  },
  {
    id: "rcpt-4",
    filename: "DESUE 1750 pg 1.pdf",
    kind: "external",
    kindLabel: "Incoming from DESUE",
    uic: "External",
    effectiveDate: "28 Aug 2026",
    lineGroups: 18,
    totalQuantity: 27,
    status: "Analyzed",
    phrhName: PHRH.fullName,
  },
  {
    id: "rcpt-5",
    filename: "APPELHOF 1750 pg 1.pdf",
    kind: "external",
    kindLabel: "Outgoing transfer",
    uic: "External",
    effectiveDate: "21 Aug 2026",
    lineGroups: 12,
    totalQuantity: 19,
    status: "Analyzed",
    phrhName: PHRH.fullName,
  },
];

export const receiptPeriods: ReceiptPeriod[] = [
  {
    id: "period-sep",
    period: "September 2026",
    effective: "01 Sep 2026",
    items: 192,
    added: 4,
    removed: 2,
    unchanged: 188,
    status: "Current",
  },
  {
    id: "period-aug",
    period: "August 2026",
    effective: "01 Aug 2026",
    items: 190,
    added: 1,
    removed: 3,
    unchanged: 186,
    status: "Reconciled",
  },
  {
    id: "period-jul",
    period: "July 2026",
    effective: "01 Jul 2026",
    items: 192,
    added: 0,
    removed: 1,
    unchanged: 191,
    status: "Reconciled",
  },
];

export const loans: LoanRecord[] = [
  {
    id: "loan-1",
    direction: "Incoming",
    document: `${DA_2062_TITLE} · DESUE`,
    item: "AN/PRC-163 Radio Set",
    serial: "10087231",
    party: "DESUE",
    signed: "28 Aug 2026",
    renewsOn: "28 Feb 2027",
    daysRemaining: 170,
    status: "Active",
  },
  {
    id: "loan-2",
    direction: "Outgoing",
    document: `${DA_2062_TITLE} · FOX`,
    item: "Dell Latitude 7430",
    serial: "J4RC6L3",
    party: "FOX",
    signed: "26 Aug 2026",
    renewsOn: "26 Feb 2027",
    daysRemaining: 168,
    status: "Active",
  },
  {
    id: "loan-3",
    direction: "Outgoing",
    document: `${DA_2062_TITLE} · E2`,
    item: "Telephone, Satellite 9575A",
    serial: "300415040404300",
    party: "E2",
    signed: "18 Apr 2026",
    renewsOn: "18 Oct 2026",
    daysRemaining: 37,
    status: "Renew soon",
  },
  {
    id: "loan-4",
    direction: "Incoming",
    document: `${DA_2062_TITLE} · BN S6`,
    item: "Cisco IRS 1101 Router",
    serial: "FGL2344LR2M",
    party: "BN S6",
    signed: "04 Apr 2026",
    renewsOn: "04 Oct 2026",
    daysRemaining: 23,
    status: "Renew soon",
  },
];

export const documents: LedgerDocument[] = [
  {
    id: "doc-1",
    filename: "18E Hand Receipt.pdf",
    kindLabel: "Hand receipt",
    date: "01 Sep 2026",
    notes: "Current unit hand receipt · PHRH R. Ortiz",
  },
  {
    id: "doc-2",
    filename: "HALE Sub-hand receipt.pdf",
    kindLabel: "Sub-hand receipt (SHR)",
    date: "01 Sep 2026",
    notes: "SHR for SPC Jordan Hale · does not relieve PHRH",
  },
  {
    id: "doc-3",
    filename: "2062 DESUE.pdf",
    kindLabel: `${DA_2062_TITLE} · incoming`,
    date: "28 Aug 2026",
    notes: "Hand Receipt/Shortage Listing",
  },
  {
    id: "doc-4",
    filename: "2062 FOX.pdf",
    kindLabel: `${DA_2062_TITLE} · outgoing`,
    date: "26 Aug 2026",
    notes: "Hand Receipt/Shortage Listing",
  },
];
